### ISSUE TITLE
Fails to compile with VS2015

### ISSUE THREAD

**Issue by zam6ak** [jacott/node-pg-libpq#1]
Hi

I get compilation errors when trying to install the package.
I am on Windows 10, x64, node v0.12.4, node-gyp v3.2.1 and VS 2015.

pg_config exists on the PATH and is valid

```
X:\Playground\node-postgresql\pg-libpq-test>pg_config --libdir
X:/Frameworks/postgresql-9.5.0-1-windows-x64-binaries/pgsql/lib
```

but npm install fails

```
X:\Playground\node-postgresql\pg-libpq-test>npm install pg-libpq --save

> pg-libpq@1.0.0 install X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq
> node-gyp rebuild


X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq>if not defined npm_config_node_gyp (node "X:\Frameworks\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  exec.cc
  pg_libpq.cc
x:\playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\src\pg_libpq.h(55): warning C4005: 'THIS': macro redefinition (compiling source file ..\src\pg_libpq.cc) [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(195): note: see previous definition of 'THIS' (compiling source file ..\src\pg_libpq.cc)
..\src\pg_libpq.cc(96): error C2065: 'uint': undeclared identifier [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(96): error C2146: syntax error: missing ';' before identifier 'len' [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(96): error C2065: 'len': undeclared identifier [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(97): error C2065: 'len': undeclared identifier [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(111): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(307): error C2131: expression did not evaluate to a constant [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
  ..\src\pg_libpq.cc(307): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\pg_libpq.cc(307): note: see usage of 'cCount'
..\src\pg_libpq.cc(309): error C3863: array type 'v8::Local<v8::String> [cCount]' is not assignable [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(318): error C2664: 'bool v8::Object::Set(uint32_t,v8::Handle<v8::Value>)': cannot convert argument 1 from 'v8::Local<v8::String> [cCount]' to 'v8::Handle<v8::Value>' [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
  ..\src\pg_libpq.cc(318): note: No constructor could take the source type, or constructor overload resolution was ambiguous
x:\playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\src\pg_libpq.h(55): warning C4005: 'THIS': macro redefinition (compiling source file ..\src\exec.cc) [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(195): note: see previous definition of 'THIS' (compiling source file ..\src\exec.cc)
..\src\exec.cc(71): error C2061: syntax error: identifier 'uint' [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\exec.cc(89): error C2065: 'uint': undeclared identifier [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\exec.cc(89): error C2146: syntax error: missing ';' before identifier 'len' [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\exec.cc(89): error C2065: 'len': undeclared identifier [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
..\src\exec.cc(90): error C2065: 'len': undeclared identifier [X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq\build\pg_libpq.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (X:\Frameworks\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "X:\\Frameworks\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd X:\Playground\node-postgresql\pg-libpq-test\node_modules\pg-libpq
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN pg-libpq-test@0.0.0 No repository field.
npm WARN pg-libpq-test@0.0.0 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "X:\\Frameworks\\nodejs\\\\node.exe" "X:\\Frameworks\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pg-libpq" "--save"
npm ERR! node v0.12.4
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! pg-libpq@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pg-libpq@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pg-libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pg-libpq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pg-libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     X:\Playground\node-postgresql\pg-libpq-test\npm-debug.log
```

**Comment by jacott** [comment]
I've replaced `uint` with `unsigned int` and published version 1.0.1.

Hopefully that fixes the problem; let me know

**Comment by zam6ak** [comment]
I tried new version and building fails with following:

```
X:\Playground\node-postgresql\node-pg-libpq>if not defined npm_config_node_gyp (node "X:\Frameworks\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  exec.cc
  pg_libpq.cc
x:\playground\node-postgresql\node-pg-libpq\src\pg_libpq.h(55): warning C4005: 'THIS': macro redefinition (compiling source file ..\src\pg_libpq.cc) [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(195): note: see previous definition of 'THIS' (compiling source file ..\src\pg_libpq.cc)
x:\playground\node-postgresql\node-pg-libpq\src\pg_libpq.h(55): warning C4005: 'THIS': macro redefinition (compiling source file ..\src\exec.cc) [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(195): note: see previous definition of 'THIS' (compiling source file ..\src\exec.cc)
..\src\pg_libpq.cc(112): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(308): error C2131: expression did not evaluate to a constant [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]
  ..\src\pg_libpq.cc(308): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\pg_libpq.cc(308): note: see usage of 'cCount'
..\src\pg_libpq.cc(310): error C3863: array type 'v8::Local<v8::String> [cCount]' is not assignable [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]
..\src\pg_libpq.cc(319): error C2664: 'bool v8::Object::Set(uint32_t,v8::Handle<v8::Value>)': cannot convert argument 1 from 'v8::Local<v8::String> [cCount]' to 'v8::Handle<v8::Value>' [X:\Playground\node-postgresql\node-pg-libpq\build \pg_libpq.vcxproj]
  ..\src\pg_libpq.cc(319): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(358): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file . .\src\exec.cc) [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]
```


I am not a C++ expert, but I tried following changes and they seem to work:

In file "**pg_libpq.cc**" make following 2 changes:

Line: 306
replace
```	int cCount = colCount;```
with
```	const int cCount = colCount;```

Line: 308
replace
```	Local<String> colNames[cCount];```
with
```	std::vector<Local<String>> colNames(cCount);   // this will require adding "#include <vector>" (line 3 or thereabouts perhaps)```

	
These changes fixed compilation errors but after doing "node-gyp configure build", I got following error:

LINK : fatal error LNK1104: cannot open file 'pq -LX:\Frameworks\postgresql-9.5.0-1-windows-x64-binaries\pgsql\lib.lib' [X:\Playground\node-postgresql\node-pg-libpq\build\pg_libpq.vcxproj]

To fix this, change "**binding.gyp**", line: 16
replace
```      'libraries' : ['-lpq -L<!@(<(pgconfig) --libdir)']```
with
```
      'conditions' : [
        ['OS=="win"', {
          'libraries' : ['libpq.lib'],
          'msvs_settings': {
            'VCLinkerTool' : {
              'AdditionalLibraryDirectories' : [
                '<!@(<(pgconfig) --libdir)\\'
              ]
            },
          }
        }, { # OS!="win"
          'libraries' : ['-lpq -L<!@(<(pgconfig) --libdir)']
        }]
      ]	
```	  
Do another "node-pg-libpq>node-gyp configure build" and .node file is generated without errors.

**Comment by jacott** [comment]
Are you able to make a pull request with your changes? 

I don't have access to a windows PC so can't verify them myself.

**Comment by jacott** [comment]
I have release version 1.0.3 which mostly incorporates the suggestions above. Hopefully this works for windows.
